### ISSUE TITLE
CUDA part fails (Typeinfo for ... undefined in device code)

### ISSUE THREAD

**Issue by tdd11235813** [ComputationalRadiationPhysics/liFFT#31]
The error message is:

> /usr/include/boost/mpl/for_each.hpp(78): error: identifier "Typeinfo for  ::mpl_::int_<(int)1> " is undefined in device code

Tested with: gcc-6+ and Boost 1.65.1, 1.66.0, 1.69.0 and CUDA 9.0+ (which requires Boost 1.65.1+).

Older versions (gcc, boost, cuda) produced different errors, but I would prefer to work on with CUDA 9+ and Boost 1.65.1+. 

The line in
```C
# test/testWrappers.cpp
    using SliceViewArgs = boost::mpl::list<int_<0>, int_<1>, int_<2>>;                                                                                                                                                                                        
# if you remove the last two arguments it will work
```

**Comment by Flamefire** [comment]
Can you try to use `std::integral_constant<int, x>` instead of the `int_`?

**Comment by tdd11235813** [comment]
I already tried, but got the same error. I first need to understand
where exactly the device information is missing, so Typeinfo (from
`<typeinfo>`?) fails when called in device code.

**Comment by Flamefire** [comment]
I investigated a bit into where this usage of RTTI is coming from. As expected it is from Boost.Test. The macro used to instantiate the test case template expands like this:

- `template_test_case_gen<TestCaseTemplate,TestTypesList>`
  - Constructor calls `generate_test_case_4_type<template_test_case_gen,TestCaseTemplate>` via mpl::for_each` on each type in `TestTypesList`
- `generate_test_case_4_type` constructs a test name based on the function name and the type used
- here `typeid(TestType).name();` is used

All of this is done on the host (it is a test after all). However the boost.MPL functions (starting at `for_each` are decorated with `BOOST_MPL_CFG_GPU_ENABLED` which expands to `__host__ __device__`. It seems that NVCC now also tries to compile function templates for device code that are called from inside such a function even when those are not marked with `__device__`, probably to support STL.

I have no idea why it would work when only 1 type is used in the list but not for all types. I'd expect it to work either for all or for none.

I would suggest to report this as a bug to NVIDIA after all this can (probably) be easily reproduced using any boost test case template.

To workaround this try to define `BOOST_NO_RTTI` which makes the function less pretty but should work otherwise.

**Comment by tdd11235813** [comment]
Thanks for the quick response! 
Just the test result: 
I just added `BOOST_NO_RTTI` definition on top before any boost unit test header is loaded. 
While the errors from above vanishes, another error pops up:
```
/opt/spack-modules/linux-ubuntu16.04-x86_64/gcc-5.4.0/boost-1.65.1-5ovw2kdz2fh44at4z3bb2d7n5n3bs4u7/include/boost/mpl/for_each.hpp(81): error: cannot use an entity undefined in device code

/usr/include/c++/5/bits/basic_string.h(271): error: cannot use an entity undefined in device code
```
Again, when reducing from three to one type in the list, it works.
(Boost 1.65.1, 1.68.0, CUDA 9.2.88, 10.0.130)

**Comment by Flamefire** [comment]
Interesting. I'm really unsure WHY this fails for multiple types. The resulting code should look something like this:

```
void foreach<int_0, int_1, int_2>(){
  run<int_0>();
  foreach<int_1, int2>();
}
void foreach<int_1, int_2>(){
  run<int_1>();
  foreach<int2>();
}
void foreach< int_2>(){
  run<int_2>();
}
```

All of it is generated at compile time so if it works for one, it should work for all... Again: I'd report this to nvidia.

Another solution would be to split this test case into a template function and manually invoking it for all params like the example here: https://www.boost.org/doc/libs/1_62_0/libs/test/doc/html/boost_test/tests_organization/test_cases/test_organization_templates.html#boost_test.tests_organization.test_cases.test_organization_templates.test_case_template_with_manual_r

**Comment by tdd11235813** [comment]
Ok, yes it does look strange. I also use mpl list and
boost::mpl::for_each in gearshifft directly and not via boost test case
template interface. Have to play around with that.
Report with MWE to Nvidia is also on TODO.

**Comment by tdd11235813** [comment]
status: 
- workaround is to use boost for_each directly and a templated function object. 
- Could not reproduce the issue in an isolated setup, must be postponed now due to other priorities
