### ISSUE TITLE
Compiler fails with gcc + cuda 7.5.18

### ISSUE THREAD

**Issue by tdd11235813** [ComputationalRadiationPhysics/liFFT#23]
Hi
for `make Test` I always get compiler errors and I think it has something to do with cuda and my local setup, since it was working in those days some months ago. With OpenCL / clfft this problem does not occur.

I have tested liFFT version from master, and added "-D_MWAITXINTRIN_H_INCLUDED" to CUDA_NVCC_FLAGS to get gcc5+ working with CUDA 7.5.
Anyway, maybe you have a hint for me. It happens for `make Test` only.

```
testWrappers.cpp
boost/test/tree/test_case_template.hpp(86): error: identifier "_ZTIN4mpl_4int_ILi1EEE" is undefined
```

It is the auto test case template thing where boost::mpl and boost::int_ is used. The typeid(...) in the mentioned line 86 can be avoided, when I define BOOST_NO_RTTI at the beginning of testWrappers.cpp. Then, the title of the case is the function name.
Occurs with gcc 4.9.1 and gcc5.3.0, also tested Boost 1.56.0 and Boost 1.60.0.

What compiler and lib versions do you use?

**Comment by Flamefire** [comment]
I was using CUDA 7.0 with gcc 4.8. Travis tests also succeed (See https://github.com/ComputationalRadiationPhysics/liFFT/blob/master/.travis.yml for the config) Boost 1.55 and 1.60 is tested.

Is gcc5+ supported by nvcc? Might be a bug there.

**Comment by tdd11235813** [comment]
yeah I guess that's it, maybe this is the first time for me, where missing gcc5 support by cuda becomes noticeable. Until now, I could run similar codes with template test cases, including our _gearshifft_ tool, with gcc5.3 and Boost 1.60.0. 
I also tested 4.9.1, but on RHEL 6.7  it is still a problem, [see this matrix here](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#axzz3x7mwvZrG), where only gcc4.4.7 would be supported last by CUDA 7.5 o_O
I'll try next days some more configurations, I guess that I used older modules on our cluster in those days.

**Comment by ax3l** [comment]
> Is gcc5+ supported by nvcc? Might be a bug there.

nah, it's not ;)
https://gist.github.com/ax3l/9489132

**Comment by tdd11235813** [comment]
it seems to be a narrow path, where liFFT/cufft-7.5 is working.
The setup given in the travis file `gcc4.8 + cuda7.5 + Boost 1.55.0` did not work on our RHEL6.7.
The following setup is working now on RHEL6.7:
- boost/1.55.0-gnu4.8
- cuda/7.5.18
- gcc/4.8.2 
- python/2.7.5-scipy
- mkl/2015 (or intel/2013)

gcc/4.8 could not handle `using ChannelType = typename ...` in tiffWriter/image.tpp

So, the liFFT readme should name environments where the FFT lib is working.
For cufft see list above and for clfft it works also with:
- cuda/7.5.18
- intel/2016.2.181                  
- fftw/3.3.4-gcc5.3-intelmpi5.1 (optional)
- opencl/1.2-4.4.0.117
- gcc/5.3.0
- boost/1.60.0-gnu5.3-intelmpi5.1
- clFFT/2.12.1-cuda7.5-gcc5.3

I run `cmake -DLiFFT_ENABLE_CUDA=0 -DLiFFT_ENABLE_OPENCL=1 ..`

**Comment by Flamefire** [comment]
You were using gcc 4.8.0? The `using` directive is a C++11 feature and should be supported by all compliant compilers. Seems 4.8.0 is not C++11 compliant.

**Comment by tdd11235813** [comment]
yup, see on [this page](https://gcc.gnu.org/gcc-4.8/cxx0x_status.html). 
gcc4.8.1 is C++11 compliant. So the travis gcc 4.8 is internally at least a gcc 4.8.1 (I am not familiar with travis how this works). And with gcc4.9.1 the compiler failed again, but I hope these things become easier with CUDA 8 which supports up to gcc5.3.

**Comment by tdd11235813** [comment]
could not reproduce it with an minimal example. gcc4.8.0 is fine with that statement, also nvcc does.
for the record, here the error message (gcc4.8.0+cuda.7.5.18+boost 1.55.0):
```
liFFT/include/tiffWriter/image.tpp:235:21: error: expected type-specifier
             using ChannelType = typename PixelType<imgFormat>::ChannelType;
                     ^
```
If you will need the extracted example (which does not fail though), here it is:
```
enum class ImageFormat                                             
{                                                                  
  ARGB, // 32bit unsigned value per pixel -> 8bit per channel      
};                                                                 
                                                                   
template< ImageFormat T_imgFormat >                                
struct PixelType;                                                  
template<>                                                         
struct PixelType< ImageFormat::ARGB >                              
{                                                                  
  using ChannelType = uint8_t;                                     
};                                                                 
                                                                   
template<ImageFormat T_imgFormat>                                  
struct SavePolicy;                                                 
template<>                                                         
struct SavePolicy< ImageFormat::ARGB >                             
{                                                                  
  static constexpr ImageFormat imgFormat = ImageFormat::ARGB;      
                                                                   
  template<typename T, typename Allocator>                         
  static void                                                      
  save(T* data, const Allocator& alloc) {                          
    using ChannelType = typename PixelType<imgFormat>::ChannelType;
    std::cout << sizeof(ChannelType) << std::endl;                 
  }                                                                
};                                                                 
                                                                   
```

**Comment by Flamefire** [comment]
Could you place any statement before the using directive in your example? Maybe typedefs must be first in a function for gcc. If so the problem is easily solved. Also moving the typedef to the class scope is possible (if that works for you)

**Comment by tdd11235813** [comment]
while the example always works (also with added statements before), the image.tpp only works with gcc4.8.0, when the using directive is moved to the class scope. Then also the tests are running with success :)
So lifft/cufft also works with gcc4.8.0 when you move this one line to the class scope.

**Comment by tdd11235813** [comment]
Btw, I plan to make a separate PR with minor changes for lifft/cufft, so I would add this fix there.

**Comment by Flamefire** [comment]
Thanks for testing that. Seems like a strange compiler bug...
Sure, looking forward to it.
